name: Keep MongoDB Awake

on:
  schedule:
    - cron: "0 0 */2 * *" # Runs every 2 days at 00:00 UTC
  workflow_dispatch:

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Send ping to backend
        run: |
          curl -X POST -c cookie.txt -d 'email=k.surendraparla1999@gmail.com' -d 'password=PKsurend@99' https://suri-food-app-api.onrender.com/api/admin/login
